# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('xp', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=100)),
                ('max_hp', models.IntegerField(default=100)),
                ('strength', models.IntegerField(default=5)),
                ('endurance', models.IntegerField(default=5)),
                ('dexterity', models.IntegerField(default=5)),
                ('willpower', models.IntegerField(default=5)),
            ],
        ),
    ]
